### ISSUE TITLE
Log of sample/wemo-insight.js

### ISSUE THREAD

**Issue by neversay** [dpjanes/homestar-wemo#3]
I can download the 0.0.7 successfully. and from the log I think iotdb can get the state of my WeMo Insight correctly, but the set(':on', true) does not work.

version:
homestar: 0.0.55
iotdb : 0.5.3
iotdb-upnp: 0.0.5
iotdb-timer: 0.0.9
homestar-wemo: 0.0.7
https://gist.github.com/neversay/38466ef3ff53228a000e

**Comment by neversay** [comment]
Here is a log file that I ran the 'homestar runner' in the same machine with the same packages:
https://gist.github.com/neversay/4d403e3d8f3dbf10001c
And it works, the light turned on/off perfectly.

**Comment by dpjanes** [comment]
In the first example, I only see an example of trying to turn it off?

```
[2015-03-04T04:09:31.136Z]  INFO: iotdb-upnp/4269 on anna1982: calling action (module=upnp/upnp-service, method=UpnpService.callAction, actionName=SetBinaryState)
    args: {
      "BinaryState": 0
    }
[2015-03-04T04:09:31.176Z]  INFO: homestar-wemo/4269 on anna1982: pushed (module=WeMoBridge, method=push)
    pushd: {
      "on": false
    }
```

**Comment by dpjanes** [comment]
Note that we're probably not reading the state correctly either on the Insight. They're returning something like
        valued: {
          "BinaryState": "0|1425398907|436|1366|60875|1209600|12|0|265365|11671950"
        }
where as we're just expecting 0 or 1. I'll put in a fix for this this morning.

**Comment by dpjanes** [comment]
I've just added parser for this and slotted into the various Model Attributes. It's in GitHub but _not_ pushed NPM.

**Comment by neversay** [comment]
Some new log with 0.0.8 when I run sample js file:
https://gist.github.com/neversay/65e5c5b1f9d39e27e8ae
I can see an error message:
{"name":"iotdb-upnp","module":"upnp/upnp-controlpoint","hostname":"anna","pid":3139,"level":30,"err":{"message":"_ is not defined","name":"ReferenceError","stack":"ReferenceError: _ is not defined\n    at Object.exports.binding.connectd.data_in (/home/pi/homestar/node_modules/homestar-wemo/models/WeMoInsight.js:53:29)\n    at _on_stateChange (/home/pi/homestar/node_modules/homestar-wemo/WeMoBridge.js:163:23)\n    at emit (events.js:107:17)\n    at Subscription.handleEvent (/home/pi/homestar/node_modules/iotdb-upnp/upnp/upnp-service.js:436:18)\n    at /home/pi/homestar/node_modules/iotdb-upnp/upnp/upnp-controlpoint.js:448:34\n    at Parser.<anonymous> (/home/pi/homestar/node_modules/iotdb-upnp/node_modules/xml2js/lib/xml2js.js:425:18)\n    at Parser.emit (events.js:107:17)\n    at Object.onclosetag (/home/pi/homestar/node_modules/iotdb-upnp/node_modules/xml2js/lib/xml2js.js:394:26)\n    at emit (/home/pi/homestar/node_modules/iotdb-upnp/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)\n    at emitNode (/home/pi/homestar/node_modules/iotdb-upnp/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)"},"msg":"{ method: 'EventHandler._serviceCallbackHandler' }","time":"2015-03-05T09:36:17.390Z","v":0}

I added some console.log in the interval and saw the console log sent, which means it indeed called the interval but the thing.set(':on', true) does not work

**Comment by neversay** [comment]
Here is another log that I ran the runner:
https://gist.github.com/neversay/ad82cd4e29abf1c29ce2
I can see the JS error still threw out, but magically the on/off WORK in the web page. Dont know how, it looks like the WeMoInsight is controlled by some other code in some place else.

**Comment by neversay** [comment]
Compared to those 2 logs, I think is the MQTT a must role in this communication mechanism?
In runner it looks like the action are driven/communicate by MQTT, and in my test script I dont have MQTT so nothing happen?

**Comment by dpjanes** [comment]
Fix pushed!

The exception (missing _ = iotdb._) is for reading the data. The writing
the data works, excellent thank you.
